# Generated by Django 4.2.1 on 2023-05-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startups',
            name='Company_Type',
            field=models.CharField(blank=True, default=None, max_length=400),
        ),
        migrations.AlterField(
            model_name='startups',
            name='Company_rank',
            field=models.CharField(blank=True, default=None, max_length=400),
        ),
        migrations.AlterField(
            model_name='startups',
            name='Name',
            field=models.CharField(blank=True, default=None, max_length=400),
        ),
        migrations.AlterField(
            model_name='startups',
            name='Status',
            field=models.CharField(blank=True, default=None, max_length=400),
        ),
        migrations.AlterField(
            model_name='startups',
            name='Website',
            field=models.CharField(blank=True, default=None, max_length=400),
        ),
        migrations.AlterField(
            model_name='startups',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=400),
        ),
    ]
